skip_branch_with_pr: true

environment:
  HOME: $(HOMEDRIVE)$(HOMEPATH)
  ANDROID_HOME: C:\android-sdk
  ANDROID_SDK_VERSION: 3859397
  BOWER_VERSION: 1.8.8
  COMPOSER_VERSION: 4.8.0
  GO_DEP_VERSION: 0.5.0
  NPM_VERSION: 6.4.0
  PHP_VERSION: 7.2.0
  SBT_VERSION: 1.0.2
  VIRTUAL_ENV_VERSION: 15.1.0
  YARN_VERSION: 1.13.0

cache:
  - $(HOME)\.gradle\caches\build-cache-1
  - $(HOME)\.gradle\caches\jars-1
  - $(HOME)\.gradle\caches\jars-2
  - $(HOME)\.gradle\caches\jars-3
  - $(HOME)\.gradle\caches\modules-2
  - $(HOME)\.gradle\caches\transforms-1
  - $(HOME)\.ivy2
  - $(HOME)\.m2\repository
  - $(HOME)\.ort\analyzer\cache\http
  - $(HOME)\.ort\analyzer\cache\remote_artifacts
  - $(HOME)\.ort\downloader\cache\http
  - $(HOME)\.ort\scanner\cache\http

clone_depth: 50

install:
  - git submodule update --init --recursive
  - npm install -g npm@%NPM_VERSION%
  - npm install -g bower@%BOWER_VERSION% yarn@%YARN_VERSION%
  - pip install virtualenv==%VIRTUAL_ENV_VERSION%
  -
  - cinst sbt --version %SBT_VERSION% -y
  - cinst php --version %PHP_VERSION% -y
  - cinst composer --version %COMPOSER_VERSION% -y # The version refers to the installer, not to Composer.
  - cd c:\tools\php72 # For some reason pushd / popd does not work.
  - copy php.ini-production php.ini
  - echo extension_dir=ext>>php.ini
  - echo extension=php_mbstring.dll>>php.ini
  - echo extension=php_openssl.dll>>php.ini
  - cd %APPVEYOR_BUILD_FOLDER%
  - cinst dep --version %GO_DEP_VERSION% -y
  - refreshenv
  - C:\msys64\usr\bin\bash -lc "pacman --noconfirm -Sy cvs"
  - set PATH=%PATH%;C:\msys64\usr\bin # For CVS.
  - set PATH=C:\Ruby25\bin;%PATH% # For licensee.
  # Install git-repo.
  - ps: Start-FileDownload 'https://storage.googleapis.com/git-repo-downloads/repo' -FileName "$env:PROGRAMFILES\Git\usr\bin\repo"
  # Install the Android SDK.
  - ps: Start-FileDownload "https://dl.google.com/android/repository/sdk-tools-windows-$env:ANDROID_SDK_VERSION.zip"
  - 7z x sdk-tools-windows-%ANDROID_SDK_VERSION%.zip -o%ANDROID_HOME% > nul
  - yes | %ANDROID_HOME%\tools\bin\sdkmanager.bat platform-tools

# Do something useful here to override the default MSBuild (which would fail otherwise).
build_script:
  - if not exist %HOME%\.gradle mkdir %HOME%\.gradle
  - echo org.gradle.daemon=false>>%HOME%\.gradle\gradle.properties
  - echo org.gradle.java.home=C:/Program Files/Java/jdk9>>%HOME%\.gradle\gradle.properties

test_script:
  - if "%APPVEYOR_SCHEDULED_BUILD%"=="True" (
      gradlew --stacktrace dokkaJar check
    ) else (
      gradlew --stacktrace -Dkotlintest.tags.exclude=ExpensiveTag check
    )

on_finish:
  - ps: |
      $url = "https://ci.appveyor.com/api/testresults/junit/$env:APPVEYOR_JOB_ID"
      $pattern = '**\build\test-results\**\TEST-*.xml'
      foreach ($file in (Resolve-Path $pattern)) {
        (New-Object 'System.Net.WebClient').UploadFile($url, $file)
      }
