skip_branch_with_pr: true

environment:
  ANDROID_HOME: C:\android-sdk
  HOME: $(HOMEDRIVE)$(HOMEPATH)

cache:
  - $(HOME)\.gradle\caches\build-cache-1
  - $(HOME)\.gradle\caches\jars-1
  - $(HOME)\.gradle\caches\jars-2
  - $(HOME)\.gradle\caches\jars-3
  - $(HOME)\.gradle\caches\modules-2
  - $(HOME)\.gradle\caches\transforms-1
  - $(HOME)\.ivy2
  - $(HOME)\.m2\repository
  - $(HOME)\.ort\analyzer\cache\http
  - $(HOME)\.ort\analyzer\cache\remote_artifacts
  - $(HOME)\.ort\downloader\cache\http
  - $(HOME)\.ort\scanner\cache\http

clone_depth: 50

install:
  - git submodule update --init --recursive
  - npm install -g bower@1.8.4 npm@6.4.0 yarn@1.9.4
  - pip install virtualenv==15.1.0
  - cinst haskell-stack --version 1.7.1 -y
  - stack setup > nul # This installs the whole GHC to an isolated location!
  - cinst php --version 7.2.0 -y
  - cinst composer --version 4.8.0 -y # The version refers to the installer, not to Composer.
  - cd c:\tools\php72 # For some reason pushd / popd does not work.
  - copy php.ini-production php.ini
  - echo extension_dir=ext>>php.ini
  - echo extension=php_mbstring.dll>>php.ini
  - echo extension=php_openssl.dll>>php.ini
  - cd %APPVEYOR_BUILD_FOLDER%
  - cinst dep --version 0.5.0 -y
  - refreshenv
  - C:\msys64\usr\bin\bash -lc "pacman --noconfirm -Sy cvs"
  - set PATH=%PATH%;C:\msys64\usr\bin # For CVS.
  - set PATH=C:\Ruby25\bin;%PATH% # For licensee.
  # Install git-repo.
  - ps: Start-FileDownload 'https://gerrit.googlesource.com/git-repo/+archive/refs/heads/master.tar.gz'
  - 7z x -so master.tar.gz | 7z x -o%APPDATA%\local\bin -si -ttar -y -i!repo
  # Install the Android SDK.
  - ps: Start-FileDownload 'https://dl.google.com/android/repository/sdk-tools-windows-3859397.zip'
  - 7z x sdk-tools-windows-3859397.zip -o%ANDROID_HOME% > nul
  - yes | %ANDROID_HOME%\tools\bin\sdkmanager.bat platform-tools

# Do something useful here to override the default MSBuild (which would fail otherwise).
build_script:
  - echo org.gradle.java.home=C:/Program Files/Java/jdk9>>%HOME%\.gradle\gradle.properties
  - gradlew dokkaJar

artifacts:
  - path: '**\build\libs\*-dokka.jar'

test_script:
  - if "%APPVEYOR_SCHEDULED_BUILD%"=="True" (
      gradlew --stacktrace check
    ) else (
      gradlew -Dkotlintest.tags.exclude=ExpensiveTag --stacktrace check
    )

on_finish:
  - gradlew --stop # Fix "fileHashes.bin" being used by another process.
  - ps: |
      $url = "https://ci.appveyor.com/api/testresults/junit/$($env:APPVEYOR_JOB_ID)"
      $pattern = '**\build\test-results\**\TEST-*.xml'
      foreach ($file in (Resolve-Path $pattern)) {
        (New-Object 'System.Net.WebClient').UploadFile($url, $file)
      }
