language: java

jdk:
  - openjdk8

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.ivy2
    - $HOME/.m2/repository/
    - $HOME/.ort/analyzer/cache/http
    - $HOME/.ort/analyzer/cache/remote_artifacts
    - $HOME/.ort/downloader/cache/http
    - $HOME/.ort/scanner/cache/http

env:
  global:
    - ANDROID_HOME="/opt/android"
    - GIMME_GO_VERSION="1.10"
    - DEP_RELEASE_TAG="v0.4.1"

install:
  - sudo apt install -y cvs
  - eval "$(gimme)"
  - curl https://raw.githubusercontent.com/golang/dep/7d5cd199ce454707f81c63b7ea4299151b8b981d/install.sh | sh
  - npm install -g npm@5.5.1 yarn@1.3.2
  - phpenv global 7.1
  - curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
  - chmod a+x ~/bin/repo
  - wget -q https://dl.google.com/android/repository/sdk-tools-linux-3859397.zip
  - unzip -q sdk-tools-linux-3859397.zip -d $ANDROID_HOME
  - yes | $ANDROID_HOME/tools/bin/sdkmanager --verbose "platform-tools"

script:
  - if git grep -L "Copyright" -- "*.kt"; then
      echo "Please add Copyright statements to the above files.";
      exit 1;
    fi
  - if ./ktlint | grep -Ev "(Wildcard import|Unexpected spacing before)"; then
      echo "Please correct above lint issues.";
      exit 1;
    fi
  - set -o pipefail
  - ./gradlew scanner:funTest --tests com.here.ort.scanner.scanners.ScanPathTest

after_success:
  - bash <(curl -s https://codecov.io/bash) -X gcov -f '!*/src/*/assets/*'

addons:
  artifacts:
    paths:
      - ./analyzer/build/reports/tests
      - ./downloader/build/reports/tests
      - ./scanner/build/reports/tests
      - ./utils/build/reports/tests
