environment:
  HOME: $(HOMEDRIVE)$(HOMEPATH)

cache:
  - $(HOME)\.gradle\caches\build-cache-1
  - $(HOME)\.gradle\caches\jars-1
  - $(HOME)\.gradle\caches\jars-2
  - $(HOME)\.gradle\caches\jars-3
  - $(HOME)\.gradle\caches\modules-2
  - $(HOME)\.gradle\caches\transforms-1
  - $(HOME)\.gradle\wrapper\dists
  - $(HOME)\.ivy2
  - $(HOME)\.m2\repository
  - $(HOME)\.ort\analyzer\cache\remote_artifacts
  - $(HOME)\.ort\analyzer\cache\http
  - $(HOME)\.ort\downloader\cache\http
  - $(HOME)\.ort\scanner\cache\http

clone_depth: 50

install:
  - git submodule update --init --recursive
  - npm install -g npm@5.5.1 yarn@1.3.2
  - pip install virtualenv==15.1.0
  - cinst sbt --version 1.0.2 -y
  - refreshenv
  - C:\msys64\usr\bin\bash -lc "pacman --noconfirm -Sy cvs"
  - set PATH=%PATH%;C:\msys64\usr\bin
  - set PATH=C:\Ruby25\bin;%PATH%
  - if "%APPVEYOR_SCHEDULED_BUILD%"=="True" (
      gem install licensee -v 9.8.0
    )

# Do something useful here to override the default MSBuild (which would fail otherwise).
build_script:
  - echo org.gradle.java.home=C:/Program Files/Java/jdk9>>%HOME%\.gradle\gradle.properties

test_script:
  - if "%APPVEYOR_SCHEDULED_BUILD%"=="True" (
      gradlew --stacktrace check
    ) else (
      gradlew -DexcludeTags=ExpensiveTag --stacktrace check
    )

on_finish:
  - gradlew --stop # Fix "fileHashes.bin" being used by another process.
  - ps: |
      $url = "https://ci.appveyor.com/api/testresults/junit/$($env:APPVEYOR_JOB_ID)"
      $pattern = '**\build\test-results\**\TEST-*.xml'
      foreach ($file in (Resolve-Path $pattern)) {
        (New-Object 'System.Net.WebClient').UploadFile($url, $file)
      }
