# SPDX-FileCopyrightText: 2024 The ORT Project Authors (see <https://github.com/oss-review-toolkit/ort/blob/main/NOTICE>)
# SPDX-License-Identifier: CC0-1.0

version = 1
SPDX-PackageName = "OSS Review Toolkit"
SPDX-PackageDownloadLocation = "https://github.com/oss-review-toolkit/ort"

[[annotations]]
path = ".**"
SPDX-FileCopyrightText = "2017 The ORT Project Authors (see <https://github.com/oss-review-toolkit/ort/blob/main/NOTICE>)"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "**/.gitattributes"
SPDX-FileCopyrightText = "2018 The ORT Project Authors (see <https://github.com/oss-review-toolkit/ort/blob/main/NOTICE>)"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "**/.gitignore"
SPDX-FileCopyrightText = "2017 The ORT Project Authors (see <https://github.com/oss-review-toolkit/ort/blob/main/NOTICE>)"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "**.json"
SPDX-FileCopyrightText = "2020 The ORT Project Authors (see <https://github.com/oss-review-toolkit/ort/blob/main/NOTICE>)"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "**.md"
SPDX-FileCopyrightText = "2017 The ORT Project Authors (see <https://github.com/oss-review-toolkit/ort/blob/main/NOTICE>)"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "**.yml"
SPDX-FileCopyrightText = "2022 The ORT Project Authors (see <https://github.com/oss-review-toolkit/ort/blob/main/NOTICE>)"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "NOTICE"
SPDX-FileCopyrightText = "2022 The ORT Project Authors (see <https://github.com/oss-review-toolkit/ort/blob/main/NOTICE>)"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "**/src/main/resources/**"
SPDX-FileCopyrightText = "2017 The ORT Project Authors (see <https://github.com/oss-review-toolkit/ort/blob/main/NOTICE>)"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "**/src/funTest/assets/**"
SPDX-FileCopyrightText = "2017 The ORT Project Authors (see <https://github.com/oss-review-toolkit/ort/blob/main/NOTICE>)"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "**/src/test/assets/**"
SPDX-FileCopyrightText = "2017 The ORT Project Authors (see <https://github.com/oss-review-toolkit/ort/blob/main/NOTICE>)"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "**/src/funTest/resources/**"
SPDX-FileCopyrightText = "2017 The ORT Project Authors (see <https://github.com/oss-review-toolkit/ort/blob/main/NOTICE>)"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "**/src/test/resources/**"
SPDX-FileCopyrightText = "2017 The ORT Project Authors (see <https://github.com/oss-review-toolkit/ort/blob/main/NOTICE>)"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "ci/**"
SPDX-FileCopyrightText = "2017 The ORT Project Authors (see <https://github.com/oss-review-toolkit/ort/blob/main/NOTICE>)"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "clients/fossid-webapp/src/test/resources/**"
SPDX-FileCopyrightText = "2020 The ORT Project Authors (see <https://github.com/oss-review-toolkit/ort/blob/main/NOTICE>)"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "clients/github-graphql/src/main/resources/**"
SPDX-FileCopyrightText = "2021 The ORT Project Authors (see <https://github.com/oss-review-toolkit/ort/blob/main/NOTICE>)"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = ".env.versions"
SPDX-FileCopyrightText = "2024 The ORT Project Authors (see <https://github.com/oss-review-toolkit/ort/blob/main/NOTICE>)"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "examples/**"
SPDX-FileCopyrightText = "2017 The ORT Project Authors (see <https://github.com/oss-review-toolkit/ort/blob/main/NOTICE>)"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "integrations/completions/**"
SPDX-FileCopyrightText = "2022 The ORT Project Authors (see <https://github.com/oss-review-toolkit/ort/blob/main/NOTICE>)"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "integrations/jenkins/**"
SPDX-FileCopyrightText = "2022 The ORT Project Authors (see <https://github.com/oss-review-toolkit/ort/blob/main/NOTICE>)"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "integrations/schemas/**"
SPDX-FileCopyrightText = "2021 The ORT Project Authors (see <https://github.com/oss-review-toolkit/ort/blob/main/NOTICE>)"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "integrations/tekton/**"
SPDX-FileCopyrightText = "2022 Google, LLC."
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "logos/**"
SPDX-FileCopyrightText = "2017 The ORT Project Authors (see <https://github.com/oss-review-toolkit/ort/blob/main/NOTICE>)"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "model/src/test/resources/test-suite-data.json"
SPDX-FileCopyrightText = "2017 the purl authors"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = "plugins/reporters/web-app-template/**"
SPDX-FileCopyrightText = "2017 The ORT Project Authors (see <https://github.com/oss-review-toolkit/ort/blob/main/NOTICE>)"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "website/**"
SPDX-FileCopyrightText = "2017 The ORT Project Authors (see <https://github.com/oss-review-toolkit/ort/blob/main/NOTICE>)"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "gradlew**"
SPDX-FileCopyrightText = "2007-2020 The original author or authors <info@gradle.com>"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "gradle/**"
SPDX-FileCopyrightText = "2007-2020 The original author or authors <info@gradle.com>"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "clients/github-graphql/src/main/resources/schema.graphql"
SPDX-FileCopyrightText = "2017 Gregor Martynus"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = "clients/osv/src/test/resources/vulnerability/examples/**"
SPDX-FileCopyrightText = "2021-2022 OSV Schema Authors"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "evaluator/src/main/resources/rules/matrixseqexpl.json"
SPDX-FileCopyrightText = "2021 Open Source Automation Development Lab (OSADL) eG"
SPDX-License-Identifier = "CC-BY-4.0"

[[annotations]]
path = "plugins/reporters/asciidoc/src/main/resources/fonts/FiraSans-**.ttf"
SPDX-FileCopyrightText = "2012-2015 The Mozilla Foundation and Telefonica S.A."
SPDX-License-Identifier = "OFL-1.1"

[[annotations]]
path = "plugins/reporters/spdx/src/funTest/resources/v2.2.2/spdx-schema.json"
SPDX-FileCopyrightText = "2020-2022 Linux Foundation and its Contributors"
SPDX-License-Identifier = "CC-BY-3.0"

[[annotations]]
path = "plugins/reporters/spdx/src/funTest/resources/v2.3/spdx-schema.json"
SPDX-FileCopyrightText = "2020-2022 Linux Foundation and its Contributors"
SPDX-License-Identifier = "CC-BY-3.0"

[[annotations]]
path = "plugins/reporters/ctrlx/src/funTest/resources/sample.fossinfo.json"
SPDX-FileCopyrightText = "2020-2021 Bosch Rexroth AG"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = "reporter/src/main/resources/prismjs/**"
SPDX-FileCopyrightText = "2012 Lea Verou"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = "utils/spdx/src/main/resources/exceptions/**"
SPDX-FileCopyrightText = "2010-2020 Linux Foundation and its Contributors"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = "utils/spdx/src/main/resources/licenses/**"
SPDX-FileCopyrightText = "2010-2020 Linux Foundation and its Contributors"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = "utils/spdx/src/main/resources/licenserefs/**"
SPDX-FileCopyrightText = "2010-2020 Linux Foundation and its Contributors"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = "utils/spdx/src/test/resources/spdx-spec-examples/**"
SPDX-FileCopyrightText = "2010-2020 Linux Foundation and its Contributors"
SPDX-License-Identifier = "CC-BY-3.0"

[[annotations]]
path = "website/static/fonts/FiraCode-Regular.woff2"
SPDX-FileCopyrightText = "2014-2020 The Fira Code Project Authors (https://github.com/tonsky/FiraCode)"
SPDX-License-Identifier = "OFL-1.1"

[[annotations]]
path = "website/static/fonts/FiraSans-Regular.woff2"
SPDX-FileCopyrightText = "2012-2015 The Mozilla Foundation and Telefonica S.A."
SPDX-License-Identifier = "OFL-1.1"
